export { PostDetails } from "./screen/detalhes-post/postDetails.screen";

export { ListarUsuariosScreen } from "./screen/listar-usuarios-page/usuarios.screen";
export { ListarSeguindoScreen } from "./screen/listar-seguindo/seguindo.screen";
export { AmigoComponent } from "./components/amigos component/amigo.components";
export { ListarAmigosScreen } from "./screen/listar amigos/amigos.screen.jsx";
export { RegisterScreen } from "./screen/register/register.screen";
export { Notificacao } from "./screen/notificacao/notificacao.screen";
export { NotificacaoComponent } from "./components/notificacao/notificacao.components";
export { Comentar } from "./components/Comentar/Comentar.component";
export { PerfilDetalhes } from "./components/perfilDetalhes/perfilDetalhes.components";
export { PerfilScreen } from "./screen/perfil/perfil.screen";
export { Post } from "./components/post/post.components";
export { LoginScreen } from "./screen/Login/Login.screen";
export { Postar } from "./components/postar/postar";
export{ Buscar } from "./screen/buscar/buscar.screen";
export{ Header } from "./components/header/header";
export{ Main } from "./screen/main/main.screen";
export{ Notices } from "./section/notices/notices.section";
export{ Utilities } from "./section/utilitys/utilities.section";
export { UsuarioPesquisado } from "./components/usuarioPesquisado/usuarioPesquisado.component";