create table permissao (id int8 generated by default as identity, nome varchar(255), user_id int8, primary key (id))
;
create table post (id int8 generated by default as identity, category varchar(255) not null, date_creation timestamp, description varchar(255) not null, usuario_id int8, primary key (id))
;
create table post_relations (posted_id int8 not null, poster_id int8 not null)
;
create table post_user_like (post_id int8 not null, user_id int8 not null)
;
create table user_relations (followed_id int8 not null, follower_id int8 not null)
;
create table user_friendly (friend_solicited_id int8 not null, friend_accept_id int8 not null)
;
create table user_request (followed_id int8 not null, follower_id int8 not null)
;
create table usuario (id int8 generated by default as identity, birth_date date,email varchar(255) not null, identify varchar(255) not null, image_perfil varchar(255), nick_name varchar(255) not null,senha varchar(255) not null, primary key (id))
;
alter table if exists usuario add constraint UK_5171l57faosmj8myawaucatdw unique (email)
;
alter table if exists usuario add constraint UK_1c5ji8g7ncwp2bi3iyxjjx7do unique (identify)
;
alter table if exists permissao add constraint FKkj3nnfwlk5d3dn0ir0cfijlg3 foreign key (user_id) references usuario
;
alter table if exists post add constraint FK27q2ean2bp3015mcu7a5ukacn foreign key (usuario_id) references usuario
;
alter table if exists post_relations add constraint FKnqcitonncr8nsr1olghp50jbw foreign key (poster_id) references post
;
alter table if exists post_relations add constraint FKapk4ck5tleq7xuule7pqfb6j4 foreign key (posted_id) references post
;
alter table if exists post_user_like add constraint FKoswqte2jyghvgwa8s9ld5apxj foreign key (user_id) references usuario
;
alter table if exists user_friendly add constraint FK3pfi059o117r1xbeavjs5353v foreign key (friend_accept_id) references usuario
;
alter table if exists post_user_like add constraint FKj12r3xvibdtthko9r7bvafno2 foreign key (post_id) references post
;
alter table if exists user_friendly add constraint FKace06omm8hscr566q419sho3b foreign key (friend_solicited_id) references usuario
;
alter table if exists user_relations add constraint FK8bbhc37jpfofwfpv13qxo07na foreign key (follower_id) references usuario
;
alter table if exists user_relations add constraint FKibhx5g81vf56dk265rpaiu4rk foreign key (followed_id) references usuario
;
alter table if exists user_request add constraint FK6rpd23l2rnl3khlqrm2b44s2o foreign key (follower_id) references usuario
;
alter table if exists user_request add constraint FK5h4xtp5fvsfxydofsbm4if20a foreign key (followed_id) references usuario
;









